
  CREATE TABLE "SYSTEM"."TBL_ORGANISATION" 
   (	"ORGANISATION_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ORGANISATION_CONTACTEMAIL" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"ORGANISATION_LOCATION" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ORGANISATION_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ORGANISATION_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ORGANISATION_CONTACTNO" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 PRIMARY KEY ("ORGANISATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
