Tables
------

CREATE TABLE TBL_USER_REGISTRATION(EMP_SRL_NUM INT NOT NULL AUTO_INCREMENT,USER_NAME VARCHAR(30),USER_PASSWORD VARCHAR(20),EMAIL VARCHAR(45),MOBILE int,USER_ROLE VARCHAR(20),CREATED_BY VARCHAR(25),CREATED_DATE DATE, CONSTRAINT EMP_SLNUM_PK PRIMARY KEY (EMP_SRL_NUM)); 

CREATE TABLE TBL_WORK_ORDER(WRK_ODR_SLNO INT NOT NULL AUTO_INCREMENT,EMP_NAME VARCHAR(40),TIME_IN VARCHAR(10),TIME_OUT VARCHAR(10),WORKED_HRS VARCHAR(10),CREATED_BY VARCHAR(30),CREATED_DATE DATE, CONSTRAINT WRK_ODR_SLNO_PK PRIMARY KEY (WRK_ODR_SLNO)
); 

CREATE TABLE TBL_STONE_DETAILS(STONE_SLNO INT NOT NULL AUTO_INCREMENT,STONE_WIDTH FLOAT(10,2),STONE_HEIGHT FLOAT(10,2),STONE_LENGTH FLOAT(10,2),STONE_TYPE VARCHAR(20),STONE_COLOUR VARCHAR(20),STONE_QTY INT,CREATED_BY VARCHAR(20),CREATED_DATE DATE, CONSTRAINT STONE_SLNO_PK PRIMARY KEY (STONE_SLNO));

CREATE TABLE TBL_STONE_IMAGES(IMAGE_SLNO INT NOT NULL AUTO_INCREMENT,STONE_IMAGE BLOB,CREATED_BY VARCHAR(20),CREATED_DATE DATE,IMAGE_FILE VARCHAR(50), CONSTRAINT IMAGE_SLNO_PK PRIMARY KEY (IMAGE_SLNO)
);


Sequences
---------

ALTER TABLE TBL_USER_REGISTRATION AUTO_INCREMENT = 1;

ALTER TABLE TBL_WORK_ORDER AUTO_INCREMENT = 1;

ALTER TABLE TBL_STONE_DETAILS AUTO_INCREMENT = 1;

ALTER TABLE TBL_STONE_IMAGES AUTO_INCREMENT = 1;
